/**
 * @fileoverview Database schema types and helper utilities
 * 
 * This file re-exports the auto-generated Supabase types and provides
 * additional helper types and utilities for working with the database.
 * 
 * The core database types are generated by the Supabase CLI and should
 * never be manually edited. They are imported from the generated file.
 */

// Re-export generated database types
export type { Database } from './generated/supabase'

// Import for type manipulation
import type { Database } from './generated/supabase'

// Helper type to extract table row types
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type TablesInsert<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type TablesUpdate<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']

// Convenient type aliases for our tables
export type Profile = Tables<'profiles'>
export type Subscription = Tables<'subscriptions'>
export type UsageCounter = Tables<'usage_counters'>

// Insert types
export type ProfileInsert = TablesInsert<'profiles'>
export type SubscriptionInsert = TablesInsert<'subscriptions'>
export type UsageCounterInsert = TablesInsert<'usage_counters'>

// Update types
export type ProfileUpdate = TablesUpdate<'profiles'>
export type SubscriptionUpdate = TablesUpdate<'subscriptions'>
export type UsageCounterUpdate = TablesUpdate<'usage_counters'>

// Extract enums from the generated types
export type SubscriptionStatus = Database['public']['Tables']['subscriptions']['Row']['status']
export type SubscriptionPlan = Database['public']['Tables']['subscriptions']['Row']['plan']

// Helper types for complex queries (these are safe to define manually)
export interface ProfileWithSubscription extends Profile {
  subscription?: Subscription
}

export interface SubscriptionWithUsage extends Subscription {
  usage_counters?: UsageCounter[]
}

// Utility function types
export type Functions<T extends keyof Database['public']['Functions']> = Database['public']['Functions'][T]

// Storage helper types
export interface FileUploadResult {
  path: string
  fullPath: string
  id: string
}
